# Generated by Django 5.0.11 on 2026-03-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_productrating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desription',
            new_name='description',
        ),
    ]
