# Generated by Django 5.0.11 on 2026-03-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
